In 10 new
jobsincub/kakJobs pull request #27
Opened 2024-12-09 07:42 UTC by Ayanqq

Added terms of service and policy privacy

2024-12-09 10:11 UTC, Ayanqq reviewed
test

2024-12-09 11:12 UTC, Ayanqq reviewed
READY

2024-12-22 15:33 UTC, Motya22 reviewed
Если что, пиши, будем разбираться)

2024-12-22 15:33 UTC, Motya22 commented on src/pages/legalInformation/ui/index.ts
> +export * from './legalLayout'
согласно FSD публичный API должен экспортировать только то, что будет использоваться вне (https://feature-sliced.design/ru/docs/reference/public-api)

2024-12-22 15:33 UTC, Motya22 commented on src/pages/legalInformation/terms-of-service.tsx
как-то ты заморочился с этими статическими страницами, я бы просто хардкодил эти параграфы)
но если сделал как ты, то я бы положил их в массив, а не в объект, чтобы можно было пройтись по нему map и отрисовать)

2024-12-22 15:33 UTC, Motya22 commented on src/pages/legalInformation/ui/legalLayout.tsx
Т.к. мы используем next, я бы сделал лэйаут с помощью специального файла в нексте - layout.tsx, создал бы Route Groups для этих двух страниц (т.е. папку в скобках) и туда положил его)

В целом, лэйаут не должен отвечать за title и paragraphs, он должен отвечать за одинаковое расположение элементов на страницах, поэтому я бы возможно вообще не создавал лэйаут для этих двух страниц, а этот компонент переименовал бы, т.к. страницы должны лежать в лэйауте, а не наоборот)

2024-12-23 11:38 UTC, Motya22 commented on src/pages/auth/verify-email/emailConfirmPage.tsx
> +      router.push('/auth/resend-verification')
Вынеси этот путь в константу в shared/router/routes.ts)

2024-12-23 15:51 UTC, jobsincub requested changes

2024-12-23 15:51 UTC, jobsincub commented on src/pages/auth/verify-email/verify-email.module.scss
> +.container {
Пройдись stylelint-ом по стилям

2024-12-23 15:51 UTC, jobsincub commented on src/pages/auth/verify-email/emailConfirmPage.tsx
> +    <div className={s.container}>
Используй компоненту Page и задай отступ с помощью пропса mt

2024-12-23 15:51 UTC, jobsincub commented on src/pages/auth/verify-email/verify-email.module.scss
> +  margin-top: 35px;
Убери отсюда марджин топ, т.к. ты его укажешь в компоненте Page

2024-12-23 15:51 UTC, jobsincub commented on src/pages/auth/verify-email/emailConfirmPage.tsx
> +      <div className={s.btnContainer}>
Лишняя обертка div, она не нужна, как и стиль s.btnContainers. Стили из btnContainer можно указать в s.button

2024-12-23 15:51 UTC, jobsincub commented on src/pages/auth/verify-email/verify-email.module.scss
> +  min-width:180px;
А почему min-width, ширина кнопки сейчас 180px ? Можно указать просто width: 180px тогда точно будет работать

2024-12-23 21:50 UTC, jobsincub requested changes

2024-12-23 21:50 UTC, jobsincub commented on src/pages/auth/verify-email/emailConfirmPage.tsx
> +  const searchParams = useSearchParams()
Вынеси логику в пользовательский хук

2024-12-23 21:50 UTC, jobsincub commented on src/pages/auth/verify-email/emailConfirmPage.tsx
> +
Давай сделаем проверку на то, если кода в урле не будет, хоть в тз это и не предусмотрено, добавь сюда дополнительно
if (!code) {
notFound()
}
Вот можешь почитать в доке, какая это прикольная штука https://nextjs.org/docs/app/api-reference/functions/not-found#version-history

2024-12-26 19:02 UTC, jobsincub approved these changes

2024-12-26 19:13 UTC, merged