In 13 resend verification
jobsincub/kakJobs pull request #30
Opened 2024-12-09 15:40 UTC by Yulia-Ya

2024-12-16 07:21 UTC, Motya22 reviewed
Как оставить в итоге решай сама)

2024-12-16 07:21 UTC, Motya22 commented on src/entities/auth/api/authApi.ts
> +    resendVerificationEmail: builder.mutation<ApiResponse<null>, ResendRegistrationArgs>({
Если тип ResendRegistrationArgs нигде больше использоваться не будет, то я бы прям в мутации "email: string" захардкодил, т.к. только один аргумент)
Если при успехе (204 код) ничего не приходит, то я бы указал вместо ApiResponse<null> - void)

2024-12-16 07:21 UTC, Motya22 commented on src/pages/auth/resendVerification/resendVerificationPage.module.scss
> +  width: 294px;
Я бы жёстко не фиксировал ширину текста, а добавил бы max-width)

2024-12-22 18:04 UTC, jobsincub requested changes
А, у тебя ворнинги еще желтые в консоли в браузере, пофиксь, пожалуйста

2024-12-22 18:04 UTC, jobsincub commented on src/features/auth/resend-verification/ui/resendVerification-form.module.scss
>  }
Отступ между инпутом и кнопкой можно было сделать флексами с помощью gap, так не придется создавать класс button

2024-12-22 18:04 UTC, jobsincub commented on src/features/auth/resend-verification/ui/resendVerification-form.tsx
>    const formSubmit = (data: ResendVerificationEmailField) => {
Оказывается эту функцию можно вообще не создавать😄, только щас это понял (надо и у себя это исправить), а передать в handleSubmit сразу onSubmit

2024-12-23 15:23 UTC, jobsincub approved these changes

2024-12-23 21:31 UTC, jobsincub requested changes
Нужно сделать интернационализацию

2024-12-26 19:22 UTC, merged