In 9 Registration
jobsincub/kakJobs pull request #37
Opened 2024-12-18 08:53 UTC by Ayanqq

Registration is Done!

2024-12-18 08:57 UTC, skitchen1992 commented on src/shared/lib/validations/passwordSchema.ts
> +    .min(6, 'Password must be at least 6 characters')
Вот это тодже нужно локализировать

2024-12-18 08:58 UTC, skitchen1992 requested changes

2024-12-18 08:58 UTC, skitchen1992 commented on src/shared/ui/controlled-textField.tsx
>      <>
Он тут не нужен

2024-12-18 13:45 UTC, Motya22 reviewed
Если что, пиши в личку в телеге)

2024-12-18 13:45 UTC, Motya22 commented on src/pages/auth/signIn/signInPage.tsx
> +    console.log(data)
скорее всего забыл console.log убрать)

2024-12-18 13:45 UTC, Motya22 commented on src/pages/auth/signUp/singUpPage.tsx
> +          <Link href={'/auth/signin'}>{signUpPage.signInLinkText}</Link>
Вынеси путь для href в константу в shared/router/routes, например, "signin: '/auth/signin'"

2024-12-18 13:45 UTC, Motya22 commented on src/pages/auth/signUp/singUpPage.module.scss
> +.pageContainer {
только это не страницы контейнер, а формы, как я понял)

2024-12-18 13:45 UTC, Motya22 commented on src/pages/auth/signUp/singUpPage.module.scss
> +  width: 100%;
Здесь это свойство лишнее, если его убрать, то ничего не изменится)

2024-12-20 05:04 UTC, Ayanqq commented on src/entities/auth/api/authApi.ts
> +    signUp: builder.mutation<ApiResponse<void>, SignUpArgs>({
вроде он возвращает всегда ApiResponse - но с пустой датой, в сваггере по крайней мере так

2024-12-20 05:36 UTC, Ayanqq commented on src/pages/auth/signUp/singUpPage.module.scss
> +.pageContainer {
здесь скорее всего pageContainer - как бы выглядит это как форма, но по самой семантике это страница, нежели форма, тут даже не знаю

2024-12-23 13:39 UTC, Motya22 commented on src/entities/auth/api/authApi.ts
> +    signUp: builder.mutation<ApiResponse<void>, SignUpArgs>({
В свагере пример для 400-го кода) 
Чтобы точно узнать попробуй отправить запрос в браузере и посмотреть вкладку Network/Response

2024-12-23 13:41 UTC, Motya22 commented on src/features/auth/signup/ui/signUp-form.module.scss
> +  gap: 24px;
Визуально разницы не будет, но не придётся создавать inputsWrapper и давать ему стили)

2024-12-23 13:46 UTC, Motya22 commented on src/pages/auth/signUp/singUpPage.module.scss
> +.pageContainer {
тогда стили для формы (max-width, padding...) я бы вынес в отдельный контейнер/обёртку для формы или прям самой форме задал

2024-12-23 17:49 UTC, jobsincub requested changes

2024-12-23 17:49 UTC, jobsincub commented on src/shared/lib/validations/confirmPasswordSchema.ts
> +    confirmPassword: z.string(),
Схема валидирования не по тз, нету сообщения, что пароли не совпадают

2024-12-23 17:49 UTC, jobsincub commented on src/shared/lib/validations/agreeTermsSchema.ts
> +export const useAgreeTermsSchema = () => {
Это схема почти 100% будет только в твоей таске, поэтому лучше убрать ее из shared и поместить папку со своей таской

2024-12-23 17:49 UTC, jobsincub commented on src/shared/lib/validations/passwordSchema.ts
> +    password: z.string().min(6, schema.minValue).regex(passwordRegex, schema.minValue).default(''),
Ты дублируешь сообщение schema.minValue, забыл про schema.regexText

2024-12-23 17:49 UTC, jobsincub commented on src/shared/lib/validations/userNameSchema.ts
> +export const useUserNameSchema = () => {
Так же схема будет только в твоей таске, нужно убрать ее из shared и перенести в свою таску

2024-12-23 17:49 UTC, jobsincub commented on src/shared/lib/validations/agreeTermsSchema.ts
> +  const agreeTermsSchema = z.object({
Забыл задать, валидацию, что этот инпут должен быть со значением true, смотри документацию https://zod.dev/?id=booleans

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/ui/signUp-form.tsx
> +  const values = watch()
Не нужная логика

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/ui/signUp-form.tsx
> +  const isFormValid =
Не нужная логика, переменную валидности isValid, нужно доставать из formState: { isValid } и использовать isValid переменную вместо самописной реализации валидности

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/lib/useSignUpForm.tsx
> +  return { control, handleSubmit, errors, watch }
Нужно убрать: errors и watch. Нужно добавить isValid

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/lib/useSignUpForm.tsx
> +    control,
Убираем errors из formState, а достать isValid

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/ui/signUp-form.tsx
> +  const formSubmit = (data: OutputSchema) => {
оказывается эта функция лишняя, нужно удалить, а в handleSubmit просто кидаем onSubmit

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/ui/signUp-form.tsx
> +    <form onSubmit={handleSubmit(formSubmit)} className={s.form}>
В handleSubmit вместо formSubmit нужно кинуть onSubmit

2024-12-23 17:49 UTC, jobsincub commented on src/shared/config/i18n/locales/en.ts
> +        agreeStart: 'I agree to the',
Из-за нового подхода от матвея, нужно будет убрать лишнее переменные start,mid...

2024-12-23 17:49 UTC, jobsincub commented on src/features/auth/signup/ui/signUp-form.tsx
> +  const {
Перемести это лучше в пользовательский хук useSignUpForm и прокинь туда signUpForm

2024-12-24 08:02 UTC, Ayanqq commented on src/features/auth/signup/lib/useSignUpForm.tsx
> +    control,
isValid не берет во внимание - когда я убираю галочку с checkBox - валидация не меняется, а мой кастомный обработчик берет во внимание, но можно попробовать чтоб я через Watch следил за чекбоксом, а isValid на все остальное

2024-12-24 12:00 UTC, Ayanqq commented on src/shared/lib/validations/confirmPasswordSchema.ts
> +    confirmPassword: z.string(),
она находится в useSignUpForm - тк мне нужно доставать значение password и сравнивать их

2024-12-24 14:24 UTC, jobsincub commented on src/features/auth/signup/lib/useSignUpForm.tsx
> +    control,
Как? А ты схему валидации написал для чекбокса, что он должен быть именно true, а не тупа boolean, я документацию кидал?

2024-12-24 16:00 UTC, jobsincub requested changes

2024-12-24 16:00 UTC, jobsincub commented on src/features/auth/signup/lib/useSignUpForm.tsx
> +      confirmPassword: '',
Ты забыл указать здесь дефолтное значение agreeTerms false

2024-12-26 06:14 UTC, closed without merging