In 23 create new password
jobsincub/kakJobs pull request #43
Opened 2024-12-23 13:13 UTC by Yulia-Ya

2024-12-23 17:50 UTC, Motya22 commented on src/features/auth/create-new-password/ui/createNewPassword-form.module.scss
> +    padding: 6px 24px;
Эти стили кнопке не нужны)

2024-12-23 21:30 UTC, jobsincub requested changes
Нужно сделать интернационализацию, ты забыла)

2024-12-23 21:30 UTC, jobsincub commented on src/pages/auth/createNewPassword/lib/useCreateNewPasswordPage.ts
> +    if (!recoveryCode) {
Сделай лучше проверку не от противного, а от положительного,
Ну то есть лучше сделай проверку на recoveryCode, и если есть, то вызывай функцию createNewPassword

2024-12-23 21:30 UTC, jobsincub commented on src/pages/auth/createNewPassword/ui/createNewPasswordPage.tsx
> +
Давай сделаем проверку на то, если кода в урле не будет, хоть в тз это и не предусмотрено, добавь сюда дополнительно
if (!recoveryCode) {
notFound()
}
Вот можешь почитать в доке, какая это прикольная штука https://nextjs.org/docs/app/api-reference/functions/not-found#version-history

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/ui/createNewPassword-form.tsx
> +  const formSubmit = (data: NewPasswordFields) => {
Эта функция лишняя, в handleSubmit используй onSubmit вместо formSubmit

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/ui/createNewPassword-form.tsx
> +    <form onSubmit={handleSubmit(formSubmit)} className={s.form}>
в handleSubmit используй onSubmit вместо formSubmit

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/ui/createNewPassword-form.tsx
> +  const { handleSubmit, control } = useCreateNewPassword()
useCreateNewPassword лучше переименовать в useCreateNewPasswordForm

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/ui/createNewPassword-form.tsx
> +
Лучше делай пробелы между строчками кода, для хорошей читаемости

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/lib/useCreateNewPassword.ts
> +    formState: { errors },
Нужно убрать errors, так как не используется, и достать отсюда isValid и его использовать для дизейбла кнопки

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/ui/createNewPassword-form.tsx
> +      <Button className={s.btn}>Create new password</Button>
Лучше сделать дизейбл кнопки, если форма не валидна, используй isValid из formState, и передай disable=!isValid

2024-12-23 21:30 UTC, jobsincub commented on src/features/auth/create-new-password/lib/useCreateNewPassword.ts
> +  return { handleSubmit, control, errors }
убрать errors и добавить isValid

2024-12-23 21:30 UTC, jobsincub commented on src/pages/auth/createNewPassword/ui/createNewPasswordPage.tsx
> +      <CreateNewPasswordForm onSubmit={onSubmit} recoveryCode={recoveryCode} />
Не нужно передавать форме recoveryCode

2024-12-26 17:24 UTC, jobsincub approved these changes

2024-12-26 18:37 UTC, merged